### ISSUE TITLE
i have this problem trying to install your package and socket io client

### ISSUE THREAD

**Issue by joselcv** [AbdoPrDZ/laravel_echo_null#2]
Because laravel_echo_null 0.0.3 depends on socket_io_client 1.0.2 and no versions of laravel_echo_null match >0.0.3 <0.1.0, laravel_echo_null ^0.0.3 requires socket_io_client 1.0.2.
So, because prosafe depends on both laravel_echo_null ^0.0.3 and socket_io_client ^2.0.2, version solving failed.

**Comment by AbdoPrDZ** [comment]
hi, i have publish an [update](https://pub.dev/packages/laravel_echo_null) and i fix this issue you can now use new version of socket.io read the Readme.md of the package for more details, you have to use `fixed-laravel-echo-server` in server side to work with new versions of socket.io-client
